创建数组的程序之二
====
From existing data，从现有的数据
----

In [131]:
import numpy as np

- array(object[, dtype, copy, order, subok, ndmin])
- asarray(a[, dtype, order])
- asanyarray(a[, dtype, order])
- ascontiguousarray(a[, dtype])
- asmatrix(data[, dtype])
- copy(a[, order])
- frombuffer(buffer[, dtype, count, offset])
- fromfile(file[, dtype, count, sep])
- `fromfunction(function, shape, **kwargs)`
- fromiter(iterable, dtype[, count])
- fromstring(string[, dtype, count, sep])
- loadtxt(fname[, dtype, comments, delimiter, …])

# numpy.array
`numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

**object :** array_like，类似数组的对象。

数组，公开数组接口的任何对象，`__array__`方法返回数组的对象，或任何（嵌套）序列。

**dtype :** data-type, 可选关键字参数。

数组所需的数据类型。如果没有给出，类型将被确定为保持序列中的对象所需的最小类型。此参数只能用于“upcast”（向上转型）数组。 对于downcasting(向下转型)，请使用.astype（t）方法。

**copy :** bool, 可选关键字参数。

如果为true（默认值），则复制对象。 否则，只有当`__array__`返回副本，obj是嵌套序列，或者需要副本来满足任何其他要求（dtype，order等）时，才会生成副本。

**order :** {‘K’, ‘A’, ‘C’, ‘F’}, 可选关键字参数。

指定数组的内存布局。如果object不是数组，则新创建的数组将按C顺序排列（行为主），除非指定了“F”，如果指定 为“F”它将采用Fortran顺序（列为主）。如果object是一个数组，则按照以下规则：

| order | no copy   | copy=True                                             |
| ----- | --------- | ----------------------------------------------------- |
| ‘K’   | unchanged | F   & C order preserved, otherwise most similar order |
| ‘A’   | unchanged | F   order if input is F and not C, otherwise C order  |
| ‘C’   | C   order | C   order                                             |
| ‘F’   | F   order | F   order                                             |

# numpy.asarray
`numpy.asarray(a, dtype=None, order=None)`

将输入转换为一个数组。

## Parameters:
**a :** array_like，输入数据，可以转换为数组的任何形式。包括列表，元组列表，元组，元组的元组，列表和ndarray的元组。

**dtype :** data-type, 数据类型，可选关键字参数。默认情况下，数据类型是从输入数据推断出来的。

**order :** {‘C’, ‘F’}, 可选关键字参数。是使用row-major（C-style）还是 column（fortranstyle）内存表示。默认为“C”。

## Returns:

输出: ndarray

a 的数组解释。如果输入已经是具有匹配的 dtype 和 order 的ndarray，则不执行复制。 如果 a 是 ndarray 的子类，则返回基类 ndarray。

In [132]:
# 将一个 list 转换为 array:

a = [1, 2]
np.asarray(a)

array([1, 2])

In [133]:
# 不复制现有的数组：

a = np.array([1, 2])
np.asarray(a) is a

True

In [134]:
# 如果已设置 dtype, 仅当 array 的 dtype 不匹配时才被复制:

a = np.array([1, 2], dtype=np.float32)
np.asarray(a, dtype=np.float32) is a

True

In [135]:
np.asarray(a, dtype=np.float64) is a

False

In [136]:
# 与asanyarray相反，ndarray子类不通过：：

issubclass(np.recarray, np.ndarray)

True

In [137]:
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
np.asarray(a) is a

False

In [138]:
np.asanyarray(a) is a

True

# numpy.asanyarray
`numpy.asanyarray(a, dtype=None, order=None)`

将输入转换为 ndarray，但通过ndarray子类转换。

## Parameters:
**a :** array_like。输入数据。任何形式的可以转换为数组的数据。包括标量，列表，元组的列表，元组，元组的元组，列表的元组和ndarray。

**dtype : **data-type, 可选关键字参数。默认情况下，data-type 是从输入的数据推断出来的。

**order :** {‘C’, ‘F’}, 可选关键字参数。

是使用row-major（C-style）还是 column（fortranstyle）内存表示。默认为“C”。

## Returns：

输出：ndarray，或者 ndarray 子类。

a 的数组解释。如果 a 是一个 ndarray 或者 ndarray的子类，它按原样返回并且不执行复制（实际就是引用）。

In [139]:
# 将一个列表转换为 array:

a = [1,2]
np.asanyarray(a)

array([1, 2])

In [140]:
# 实例化 ndarray 子类是通过原样（as-is）进行的：
a = np.array([(1.0,2),(3.0,4)],dtype='f4,i4').view(np.recarray)
np.asanyarray(a) is a

True

# numpy.ascontiguousarray
`numpy.ascontiguousarray(a, dtype=None)`

返回一个在内存（C 顺序）中相连的数组。

## Parameters:

**a :**  array_like，输入数组。

**dtype :** str or dtype object, 可选关键字参数，返回数组的数据类型。

## Returns:	
输出: ndarray

相邻的数组的 shape 和内容与 a 相同，dtype是指定的。

In [141]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
np.ascontiguousarray(x,dtype=np.float32)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]], dtype=float32)

In [143]:
x.flags['C_CONTIGUOUS']

True

# numpy.asmatrix
`numpy.asmatrix(data, dtype=None)`

将输入编译为一个 matrix.

不同于 matrix, 如果输入已经是一个 matrix 或者 ndarray，asmatrix 不生成一个拷贝。等价于 `matrix(data, copy=False)`.

## Parameters:
**data :** array_like，输入数据。

**dtype :** data-type，输出 matrix 的数据类型。

## Returns:
**mat :** matrix，数据被编译为一个 matrix.

In [144]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [145]:
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [146]:
x is m

False

In [147]:
n = np.asmatrix(m)

In [148]:
n is m

True

# numpy.copy
`numpy.copy(a, order='K')`

返回给定对象的数组副本。

## Parameters:
**a :** array_like，输入的数据.

**order :** {‘C’, ‘F’, ‘A’, ‘K’}, 可选关键字参数。控制副本的内存布局。 ‘C’ 意指 C-order, ‘F’ 意指 F-order, 如果a是与Fortran相邻的，‘A’ 意指 ‘F’,否则意指 ‘C’. ‘K’ 意指尽可能接近a的布局。 (注意：这个函数与 ndarray.copy非常近似，但是它们的order = arguments的默认值不同。)

## Returns: 
arr : ndarray

a 的数组解释。

**注意**

这个等价于：`np.array(a, copy=True) `

In [149]:
# 创建一个数组x，y引用x, z复制x:

x = np.array([1,2,3])
y= x
z = np.copy(x)

#注意：当我们修改 x 时，y 会变化，但z不会。

In [150]:
x[0]=10
x[0]==y[0]

True

In [151]:
x[0]==z[0]

False

# numpy.frombuffer
`numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)`

将缓存解读为 1-D array.

## Parameters:	
**buffer :** buffer_like 一个暴露了缓冲区接口的对象。

**dtype :** data-type, 可选关键字参数。返回的 array的数据类型，默认为：float.

**count :** int, 可选关键字参数。要读的条目数量。-1 意味着缓冲区的所有数据。

**offset :** int, 可选关键字参数。从这个偏移位置开始读取缓冲区（字节数）；默认为：0

**注意：**如果缓冲区中没有机器字节顺序的数据，那么应该将其指定为数据类型的一部分，例如：

```
dt = np.dtype(int)
dt = dt.newbyteorder('>')
np.frombuffer(buf, dtype=dt)
```

生成的数组的数据不会被字节交换，但会被正确解读。

In [152]:
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'],
      dtype='|S1')

# numpy.fromfile
`numpy.fromfile(file, dtype=float, count=-1, sep='')`

从文本或二进制文件中的数据构造一个 array.

一种非常高效的方法，可以用已知的数据类型来读取二进制数据，以及解析简单格式化的文本文件。使用tofile方法编写的数据可以使用这个函数读取。

## Parameters:
**file :** file or str，打开文件对象，或文件名。

**dtype :** data-type，返回数组的数据类型。对于二进制文件，它被用于确定文件中条目的大小 和字节顺序。

**count :** int，读取条目的数量。-1 表示所有条目（如，完整的文件）。

**sep :** str，如果file是一个文本文件，两个条目之间的分隔符。 空（“”）分隔符意味着文件将被视作二进制处理。

分隔符中的空格（“”）匹配零个或多个空格字符。仅由空格组成的分隔符必须匹配至少一个空格。

**注意：**

不要依赖于tofile和fromfile的组合来进行数据存储，因为生成的二进制文件不是独立于平台的。 特别是，不保存字节顺序或数据类型信息。 数据可以使用保存和加载以平台独立的.npy格式存储。

In [153]:
# 构造一个 ndarray:

dt = np.dtype([('time', [('min', int), ('sec', int)]),
                ('temp', float)])
dt

dtype([('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])

In [178]:
x = np.zeros((1,), dtype='b')
x

array([0], dtype=int8)

In [179]:
# Save the raw data to disk:

import tempfile
fname = tempfile.TemporaryFile('w+b')
fname.write(x)

1

In [184]:
# Read the raw data from disk:

np.fromfile(fname, dtype=dt)

array([], dtype=float64)

In [186]:
# The recommended way to store and load data:

np.save(fname, x)
np.load(fname + '.npy')

OSError: [Errno 22] Invalid argument: '<tempfile._TemporaryFileWrapper object at 0x000001EC2D2F5F98>.npy'