创建数组的程序之二
====
From existing data，从现有的数据
----

In [33]:
import numpy as np

- array(object[, dtype, copy, order, subok, ndmin])
- asarray(a[, dtype, order])
- asanyarray(a[, dtype, order])
- ascontiguousarray(a[, dtype])
- asmatrix(data[, dtype])
- copy(a[, order])
- frombuffer(buffer[, dtype, count, offset])
- fromfile(file[, dtype, count, sep])
- `fromfunction(function, shape, **kwargs)`
- fromiter(iterable, dtype[, count])
- fromstring(string[, dtype, count, sep])
- loadtxt(fname[, dtype, comments, delimiter, …])

# numpy.array
`numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

**object :** array_like，类似数组的对象。

数组，公开数组接口的任何对象，`__array__`方法返回数组的对象，或任何（嵌套）序列。

**dtype :** data-type, 可选关键字参数。

数组所需的数据类型。如果没有给出，类型将被确定为保持序列中的对象所需的最小类型。此参数只能用于“upcast”（向上转型）数组。 对于downcasting(向下转型)，请使用.astype（t）方法。

**copy :** bool, 可选关键字参数。

如果为true（默认值），则复制对象。 否则，只有当`__array__`返回副本，obj是嵌套序列，或者需要副本来满足任何其他要求（dtype，order等）时，才会生成副本。

**order :** {‘K’, ‘A’, ‘C’, ‘F’}, 可选关键字参数。

指定数组的内存布局。如果object不是数组，则新创建的数组将按C顺序排列（行为主），除非指定了“F”，如果指定 为“F”它将采用Fortran顺序（列为主）。如果object是一个数组，则按照以下规则：

| order | no copy   | copy=True                                             |
| ----- | --------- | ----------------------------------------------------- |
| ‘K’   | unchanged | F   & C order preserved, otherwise most similar order |
| ‘A’   | unchanged | F   order if input is F and not C, otherwise C order  |
| ‘C’   | C   order | C   order                                             |
| ‘F’   | F   order | F   order                                             |

# numpy.asarray
`numpy.asarray(a, dtype=None, order=None)`

将输入转换为一个数组。

## Parameters:
**a :** array_like，输入数据，可以转换为数组的任何形式。包括列表，元组列表，元组，元组的元组，列表和ndarray的元组。

**dtype :** data-type, 数据类型，可选关键字参数。默认情况下，数据类型是从输入数据推断出来的。

**order :** {‘C’, ‘F’}, 可选关键字参数。是使用row-major（C-style）还是 column（fortranstyle）内存表示。默认为“C”。

## Returns:

输出: ndarray

a 的数组解释。如果输入已经是具有匹配的 dtype 和 order 的ndarray，则不执行复制。 如果 a 是 ndarray 的子类，则返回基类 ndarray。

In [34]:
# 将一个 list 转换为 array:

a = [1, 2]
np.asarray(a)

array([1, 2])

In [35]:
# 不复制现有的数组：

a = np.array([1, 2])
np.asarray(a) is a

True

In [36]:
# 如果已设置 dtype, 仅当 array 的 dtype 不匹配时才被复制:

a = np.array([1, 2], dtype=np.float32)
np.asarray(a, dtype=np.float32) is a

True

In [37]:
np.asarray(a, dtype=np.float64) is a

False

In [38]:
# 与asanyarray相反，ndarray子类不通过：：

issubclass(np.recarray, np.ndarray)

True

In [39]:
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
np.asarray(a) is a

False

In [40]:
np.asanyarray(a) is a

True

# numpy.asanyarray
`numpy.asanyarray(a, dtype=None, order=None)`

将输入转换为 ndarray，但通过ndarray子类转换。

## Parameters:
**a :** array_like。输入数据。任何形式的可以转换为数组的数据。包括标量，列表，元组的列表，元组，元组的元组，列表的元组和ndarray。

**dtype : **data-type, 可选关键字参数。默认情况下，data-type 是从输入的数据推断出来的。

**order :** {‘C’, ‘F’}, 可选关键字参数。

是使用row-major（C-style）还是 column（fortranstyle）内存表示。默认为“C”。

## Returns：

输出：ndarray，或者 ndarray 子类。

a 的数组解释。如果 a 是一个 ndarray 或者 ndarray的子类，它按原样返回并且不执行复制（实际就是引用）。

In [41]:
# 将一个列表转换为 array:

a = [1,2]
np.asanyarray(a)

array([1, 2])

In [42]:
# 实例化 ndarray 子类是通过原样（as-is）进行的：
a = np.array([(1.0,2),(3.0,4)],dtype='f4,i4').view(np.recarray)
np.asanyarray(a) is a

True

# numpy.ascontiguousarray
`numpy.ascontiguousarray(a, dtype=None)`

返回一个在内存（C 顺序）中相连的数组。

## Parameters:

**a :**  array_like，输入数组。

**dtype :** str or dtype object, 可选关键字参数，返回数组的数据类型。

## Returns:	
输出: ndarray

相邻的数组的 shape 和内容与 a 相同，dtype是指定的。

In [43]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.ascontiguousarray(x,dtype=np.float32)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]], dtype=float32)

In [45]:
x.flags['C_CONTIGUOUS']

True

# numpy.asmatrix
`numpy.asmatrix(data, dtype=None)`

将输入编译为一个 matrix.

不同于 matrix, 如果输入已经是一个 matrix 或者 ndarray，asmatrix 不生成一个拷贝。等价于 `matrix(data, copy=False)`.

## Parameters:
**data :** array_like，输入数据。

**dtype :** data-type，输出 matrix 的数据类型。

## Returns:
**mat :** matrix，数据被编译为一个 matrix.

In [46]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [47]:
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [48]:
x is m

False

In [51]:
n = np.asmatrix(m)

In [52]:
n is m

True

# numpy.copy
`numpy.copy(a, order='K')`

返回给定对象的数组副本。

## Parameters:
**a :** array_like，输入的数据.

**order :** {‘C’, ‘F’, ‘A’, ‘K’}, 可选关键字参数。控制副本的内存布局。 ‘C’ 意指 C-order, ‘F’ 意指 F-order, 如果a是与Fortran相邻的，‘A’ 意指 ‘F’,否则意指 ‘C’. ‘K’ 意指尽可能接近a的布局。 (注意：这个函数与 ndarray.copy非常近似，但是它们的order = arguments的默认值不同。)

## Returns: 
arr : ndarray

a 的数组解释。

**注意**

这个等价于：`np.array(a, copy=True) `

In [ ]:
Create an array x, with a reference y and a copy z:

>>>
>>> x = np.array([1, 2, 3])
>>> y = x
>>> z = np.copy(x)
Note that, when we modify x, y changes, but not z:

>>>
>>> x[0] = 10
>>> x[0] == y[0]
True
>>> x[0] == z[0]
False

In [54]:
# 创建一个数组x，y引用x, z复制x:

x = np.array([1,2,3])
y= x
z = np.copy(x)

#注意：当我们修改 x 时，y 会变化，但z不会。

In [56]:
x[0]=10
x[0]==y[0]

True

In [57]:
x[0]==z[0]

False

# numpy.frombuffer
numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
Interpret a buffer as a 1-dimensional array.

Parameters:	
buffer : buffer_like
An object that exposes the buffer interface.

dtype : data-type, optional
Data-type of the returned array; default: float.

count : int, optional
Number of items to read. -1 means all data in the buffer.

offset : int, optional
Start reading the buffer from this offset (in bytes); default: 0.