12-创建数组的程序之七
====
The Matrix class
----

# numpy.mat
`numpy.mat(data, dtype=None)

将输入解译为一个矩阵。

与 matrix 不同的是，如果输入已经是一个矩阵或ndarray，那么asmatrix就不会复制它。相当于matrix(data,copy= False)。

## Parameters:	
**data :** array_like，输入数据。

**dtype :** data-type，输出矩阵的数据类型。

## Returns:	
mat : matrix

data被解译为一个矩阵。

## 示例

In [2]:
import numpy as np
>>> x = np.array([[1, 2], [3, 4]])
>>> m = np.asmatrix(x)
>>> x[0,0] = 5
>>> m

matrix([[5, 2],
        [3, 4]])

# numpy.bmat
`numpy.bmat(obj, ldict=None, gdict=None)`

从字符串，嵌套的序列，或array构造一个matrix对象。

## Parameters:	
**obj :** str or array_like 输入的数据。如果是一个字符串，可以通过名称来引用当前作用域的变量。

**ldict :** dict, 可选关键字参数。替换当前帧中的本地操作数的字典。 如果obj不是字符串，则忽略或gdict为None。

**gdict :** dict, 可选关键字参数。在当前帧中替换全局操作数的词典。如果obj不是字符串，就会忽略它。

## Returns:	
out : matrix

返回一个matrix对象，它是一个专门的 2-D array.

## 示例

In [4]:
>>> A = np.mat('1 1; 1 1')
>>> B = np.mat('2 2; 2 2')
>>> C = np.mat('3 4; 5 6')
>>> D = np.mat('7 8; 9 0')

下列表达式构造相同的块矩阵：

In [8]:
>>> np.bmat([[A, B], [C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [9]:
>>> np.bmat(np.r_[np.c_[A, B], np.c_[C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [10]:
>>> np.bmat('A,B; C,D')

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])