Input and Output 之二
====

Text files
----

| Text   files                                    |                                                              |
| ----------------------------------------------- | ------------------------------------------------------------ |
| loadtxt(fname[, dtype, comments, delimiter, …]) | Load   data from a text file.                                |
| savetxt(fname, X[, fmt, delimiter, newline, …]) | Save   an array to a text file.                              |
| genfromtxt(fname[, dtype, comments, …])         | Load   data from a text file, with missing values handled as specified. |
| fromregex(file, regexp, dtype[, encoding])      | Construct   an array from a text file, using regular expression parsing. |
| fromstring(string[, dtype, count, sep])         | A   new 1-D array initialized from text data in a string.    |
| ndarray.tofile(fid[, sep, format])              | Write   array to a file as text or binary (default).         |
| ndarray.tolist()                                | Return   the array as a (possibly nested) list.              |

# numpy.loadtxt
`numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')`

从文本文件加载数据。

文本文件中的每一行必须具有相同数量的值。

## Parameters:	
**fname** : file, str, or pathlib.Path

要读取的文件，文件名或生成器。如果文件扩展名为 `.gz`或`.bz2`，则首先解压缩文件。请注意，生成器应返回Python 3k的字节字符串。

**dtype** : data-type, optional

结果数组的数据类型; 默认值：float。如果这是结构化数据类型，则生成的数组将是1维的，并且每行将被解释为数组的元素。在这种情况下，使用的列数必须与数据类型中的字段数相匹配。

**comments** : str or sequence of str, optional

用于表示评论开头的字符或字符列表。None 意味着没有评论。为了向后兼容，字节字符串将被解码为'latin1'。默认值为“＃”。

**delimiter** : str, optional

用于分隔值的字符串。为了向后兼容，字节字符串将被解码为'latin1'。默认值为空格。

**converters** : dict, optional

将列号映射到将列字符串解析为所需值的函数的字典。例如，如果第0列是日期字符串：`converters = {0: datestr2num}.`。转换器也可以用于提供丢失数据的默认值（但也可以看到genfromtxt）：`converters = {3: lambda s: float(s.strip() or 0)}. Default: None.` 。默认值：无。

**skiprows** : int, optional

跳过第一个skiprows行数 ; 默认值：0。

**usecols** : int or sequence, optional

要读取哪些列，其中0为第一列。例如， `usecols = (1,4,5)` 将提取第2列，第5列和第6列。默认值None，读取所有列。

在版本1.11.0中更改：当必须读取单个列时，可以使用整数而不是元组。例如，`usecols = 3`以与`usecols = (3,)`相同的方式读取第四列。

**unpack** : bool, optional

如果为True，则返回的数组被转置，以便可以使用`x, y, z = loadtxt(...)`解压缩参数。与结构化数据类型一起使用时，将为每个字段返回数组。默认值为False。

**ndmin** : int, optional

返回的数组至少具有ndmin维度。否则将挤压单维轴。合法值：0（默认值），1或2。

版本1.6.0中的新功能。

**encoding** : str, optional

用于解码输入文件的编码。不适用于输入流。特殊值'bytes'启用向后兼容性解决方法，确保在可能的情况下接收字节数组作为结果，并将'latin1'编码的字符串传递给转换器。重写此值以接收unicode数组并将字符串作为输入传递给转换器。如果设置为“无”，则使用系统默认值。默认值为'bytes'。

1.14.0版中的新功能。

## Returns:

**out** : ndarray，从文本文件中读取的数据。

**注意：**

此功能旨在成为简单格式化文件的快速读取器。`genfromtxt`功能提供更复杂的处理，例如具有缺失值的行。

版本1.10.0中的新功能。

Python `float.hex`方法生成的字符串可以用作浮点数的输入。

## 示例

In [21]:
import numpy as np
>>> from io import StringIO   # StringIO behaves like a file object
>>> c = StringIO(u"0 1\n2 3")
>>> np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

In [22]:
>>> d = StringIO(u"M 21 72\nF 35 58")
>>> np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
...                      'formats': ('S1', 'i4', 'f4')})

array([(b'M', 21, 72.), (b'F', 35, 58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [23]:
>>> c = StringIO(u"1,0,2\n3,0,4")
>>> x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)
>>> x

array([1., 3.])

In [24]:
>>> y

array([2., 4.])

# numpy.savetxt
`numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)`

将一个数组保存到文本文件中。

## Parameters:	
**fname** : filename or file handle

如果文件名以`.gz`结束，文件将自动以压缩的`gzip`格式保存。 loadtxt 清晰地理解 gzip 文件。

**X**: 1D or 2D array_like

要保存到文本文件的数据。

**fmt** : str or sequence of strs, optional

单个格式（`％10.5f`），格式序列或多格式字符串，例如“`Iteration ％d - ％10.5f`”，在这种情况下，将忽略分隔符。对于复杂的`X`，`fmt`的合法选项是：
- 单个说明符，`fmt ='％。4e'`，导致数字格式为`'（％s +％sj）'％（fmt，fmt）`
- 一个完整的字符串，指定每个实部和虚部，例如` '％.4e％+.4ej％.4e％+.4ej％.4e％+.4ej'`为3列
- 一个说明符列表，每列一个 `-` 在这种情况下，实部和虚部必须有单独的说明符，例如`['％.3e +％.3ej'，'（％.15e％+.15ej）']` 2列

**delimiter** : str, optional

分隔列的字符串或字符。

**newline** : str, optional

字符串或字符分隔线。

1.5.0版中的新功能。

**header** : str, optional

将在文件开头写入的字符串。

版本1.7.0中的新功能。

**footer** : str, optional

将在文件末尾写入的字符串。

版本1.7.0中的新功能。

**comments** : str, optional

将附加到header和footer字符串的字符串，以将其标记为注释。默认值：`'＃'`，正如预期的那样` numpy.loadtxt`。

版本1.7.0中的新功能。

**encoding** : {None, str}, optional

用于编码输出文件的编码。不适用于输出流。如果编码不是'bytes'或'latin1'，您将无法在`NumPy`版本`<1.14`中加载该文件。默认为'latin1'。

1.14.0版中的新功能。

**注意：**

fmt参数（`%[flag]width[.precision]specifier`）的进一步说明：

**flags:**
- `-` ：左对齐
- `+` ：强制在结果前面加上+或 - 。
- `0` ：用零填充数字而不是空格（参见 width）。

**width:**

要打印的最小字符数。如果该字符包含更多字符，则不会截断该值。

**precision:** 精度
- 对于整数说明符（例如d,i,o,x），最小位数。
- For 和说明符，小数点后打印的位数。e, Ef
- 对于g和G，最大有效位数。
- 对于s，最大字符数。

**specifiers:** 标识符
> c : character，字符

> d or i : signed decimal integer，带符号的十进制整数。

> e or E : scientific notation with e or E. 带e或E的科学记数法。

> f : decimal floating point，十进制浮点数。

> g,G : use the shorter of e,E or f，使用较短的e, E 或 f。

> o : signed octal，带符号的八进制数。

> s : string of characters，字符的字符串。

> u : unsigned decimal integer，无符号的十进制整数。

> x,X : unsigned hexadecimal integer，无符号的十六进制整数。

这种解释fmt并不完整，详尽的说明见 [Format Specification Mini-Language](https://docs.python.org/3/library/string.html#format-specification-mini-language)

## 示例

In [25]:
>>> x = y = z = np.arange(0.0,5.0,1.0)
>>> np.savetxt('test.out', x, delimiter=',')   # X is an array
>>> np.savetxt('test.out', (x,y,z))   # x,y,z equal sized 1D arrays
>>> np.savetxt('test.out', x, fmt='%1.4e')   # use exponential notation

# numpy.genfromtxt
`numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')`

从文本文件加载数据，并按指定处理缺失值。

超过第一个skip_header行的每一行将以分隔符分割 ，并且将丢弃注释字符后面的字符。

## Parameters:	
**fname** : file, str, pathlib.Path, list of str, generator

要读取的文件，文件名，列表或生成器。如果文件扩展名为`gz`或`bz2`，则首先解压缩文件。请注意，在Python 3k中生成器必须返回字节字符串。列表中的字符串或生成器生成的字符串被视为行。

**dtype** : dtype, optional

结果数组的数据类型。如果为None，则dtypes将由每列的内容单独确定。

**comments** : str, optional

用于表示评论开始的字符。注释后出现在行上的所有字符都将被丢弃

**delimiter** : str, int, or sequence, optional

用于分隔值的字符串。默认情况下，任何连续的空格都用作分隔符。也可以提供整数或整数序列作为每个字段的宽度。

**skiprows** : int, optional

在numpy 1.10中删除了skiprows。请改用skip_header。

**skip_header** : int, optional

要在文件形状开头跳过的行数。

**skip_footer** : int, optional

要在文件末尾跳过的行数。

**converters** : variable, optional

将列数据转换为值的函数集。转换器还可用于为丢失的数据提供默认值：`converters = {3: lambda s: float(s or 0)}`

**missing** : variable, optional

在numpy 1.10中删除了缺失。请改用missing_values。

**missing_values** : variable, optional

与缺失数据相对应的字符串集。

**filling_values** : variable, optional

缺少数据时要用作默认值的值集。

**usecols** : sequence, optional

要读取哪些列，其中0为第一列。例如， `usecols = (1, 4, 5)`将提取第2列，第5列和第6列。

**names** : {None, True, str, sequence}, optional

如果names为True，则在第一个skip_header行之后的第一行读取字段名称。此行可以选择由注释分隔符继续。如果names是序列或逗号分隔名称的单字符串，则名称将用于定义结构化dtype中的字段名称。如果names为None，则将使用dtype字段的名称（如果有）。

**excludelist** : sequence, optional

要排除的名称列表。此列表将附加到默认列表`['return'，'file'，'print']`。排除的名称附加下划线：例如，`file`将成为`file_`。

**deletechars** : str, optional

必须从名称中删除的无效字符组合的字符串。

**defaultfmt** : str, optional

用于定义默认字段名称的格式，例如`“f％i”`或`“f_％02i”`。

**autostrip** : bool, optional

是否从变量中自动剥离空格。

**replace_space** : char, optional

用于替换变量名称中的空格的字符。默认情况下，使用`“_”`。

**case_sensitive** : `{True, False, ‘upper’, ‘lower’}`, optional

如果为True，则字段名称区分大小写。如果为False或'upper'，则字段名称将转换为大写。如果为“lower”，则字段名称将转换为小写。

**unpack** : bool, optional

如果为True，则返回的数组被转置，以便可以使用`x, y, z = loadtxt(...)`解压缩参数 

**usemask** : bool, optional

如果为True，则返回一个掩码数组。如果为False，则返回常规数组。

**loose** : bool, optional

如果为True，请不要为无效值引发错误。

**invalid_raise** : bool, optional

如果为True，则在列数中检测到不一致时会引发异常。如果为False，则发出警告并跳过违规行。

**max_rows** : int, optional

要读取的最大行数。不得与skip_footer同时使用。如果给定，则值必须至少为1.默认值是读取整个文件。

版本1.10.0中的新功能。

**encoding** : str, optional

用于解码输入文件的编码。当fname是文件对象时不适用。特殊值'bytes'启用向后兼容性解决方法，确保在可能的情况下接收字节数组并将latin1编码的字符串传递给转换器。重写此值以接收unicode数组并将字符串作为输入传递给转换器。如果设置为“无”，则使用系统默认值。默认值为'bytes'。

1.14.0版中的新功能。

## Returns:	
out : ndarray

从文本文件中读取的数据。如果usemask为True，则这是一个掩码数组。

**注意：**

- 当空格用作分隔符时，或者没有给定分隔符作为输入时，两个字段之间不应该有任何丢失的数据。
- 当命名变量时（通过灵活的dtype或使用名称），文件中不得有任何数据头（否则会引发ValueError异常）。
- 默认情况下，不会删除单个值的空格。使用自定义转换器时，请确保该功能确实删除了空格。

## 示例

In [26]:
>>> from io import StringIO
>>> import numpy as np

带混合dtype的逗号分隔文件：

In [27]:
>>> s = StringIO(u"1,1.3,abcde")
>>> data = np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),
... ('mystring','S5')], delimiter=",")
>>> data

array((1, 1.3, b'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', 'S5')])

使用 `dtype = None`

In [28]:
>>> s.seek(0) # needed for StringIO example only
>>> data = np.genfromtxt(s, dtype=None,
... names = ['myint','myfloat','mystring'], delimiter=",")
>>> data

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array((1, 1.3, b'abcde'),
      dtype=[('myint', '<i4'), ('myfloat', '<f8'), ('mystring', 'S5')])

指定 dtype 和 names:

In [29]:
>>> s.seek(0)
>>> data = np.genfromtxt(s, dtype="i8,f8,S5",
... names=['myint','myfloat','mystring'], delimiter=",")
>>> data

array((1, 1.3, b'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', 'S5')])

固定宽度列的一个例子:

In [30]:
>>> s = StringIO(u"11.3abcde")
>>> data = np.genfromtxt(s, dtype=None, names=['intvar','fltvar','strvar'],
...     delimiter=[1,3,5])
>>> data

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array((1, 1.3, b'abcde'),
      dtype=[('intvar', '<i4'), ('fltvar', '<f8'), ('strvar', 'S5')])

# numpy.fromregex
`numpy.fromregex(file, regexp, dtype, encoding=None)`

从文本文件构造一个数组，使用正则表达式对其进行解析。

返回的数组始终是结构化数组，并且是根据文件中正则表达式的所有匹配构造的。正则表达式中的组将转换为结构化数组的字段。

## Parameters:	
**file** : str or file

要读取的文件名或文件对象。

**regexp** : str or regexp

用于解析文件的正则表达式。正则表达式中的组对应于dtype中的字段。

**dtype** : dtype or list of dtypes

适合于结构化数组的dtype。

**encoding** : str, optional

用于解码输入文件的编码。不适用于输入流。

1.14.0版中的新功能。

## Returns:	
output : ndarray

输出数组，包含由regexp匹配的文件内容的一部分。输出始终是结构化数组。

**Raises**:

TypeError
当dtype对于结构化数组来说不是有效的dtype时。

**注意：**

结构化数组的Dtypes可以以多种形式指定，但所有表单至​​少指定数据类型和字段名称。详情见 [doc.structured_arrays](https://docs.scipy.org/doc/numpy/user/basics.rec.html#module-numpy.doc.structured_arrays)

## 示例

In [31]:
>>> f = open('test.dat', 'w')
>>> f.write("1312 foo\n1534  bar\n444   qux")
>>> f.close()

In [32]:
>>> regexp = r"(\d+)\s+(...)"  # match [digits, whitespace, anything]
>>> output = np.fromregex('test.dat', regexp,
...                       [('num', np.int64), ('key', 'S3')])
>>> output

array([(1312, b'foo'), (1534, b'bar'), ( 444, b'qux')],
      dtype=[('num', '<i8'), ('key', 'S3')])

In [33]:
>>> output['num']

array([1312, 1534,  444], dtype=int64)

# numpy.fromstring
`numpy.fromstring(string, dtype=float, count=-1, sep='')`

从字符串中的文本数据初始化的新1-D数组。

## Parameters:	
**string** : str

包含数据的字符串。

**dtype** : data-type, optional

数组的数据类型; 默认值：float。对于二进制输入数据，数据必须采用这种格式。

**count** : int, optional

从数据中读取此数量的dtype元素。如果这是负数（默认值），则计数将根据数据的长度确定。

**sep** : str, optional

用于分隔数据中的数字的字符串; 元素之间的额外空格也被忽略。

自1.14版本后不推荐使用：如果未提供此参数，fromstring返回frombuffer的行为，在编码unicode字符串输入为utf-8(python3)，或默认的编码以后。

## Returns:	
arr : ndarray

构造数组。

## Raises:	
ValueError， 如果字符串的大小不正确，无法满足请求的 dtype 和 count。

## 示例

In [34]:
>>> np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [35]:
>>> np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

# numpy.ndarray.tofile
`ndarray.tofile(fid, sep="", format="%s")`

将数组作为文本或二进制写入文件（默认）。

数据始终以“C”顺序写入，与a的顺序无关。可以使用fromfile（）函数恢复此方法生成的数据。

## Parameters:	
**fid** : file or str

打开的文件对象或包含文件名的字符串。

**sep** : str
用于文本输出的数组项之间的分隔符。如果“”（空），则写入二进制文件，相当于 file.write(a.tobytes())。

**format** : str

文本文件输出的格式字符串。通过首先将数组转换为最接近的Python类型，然后使用“format”％item，将数组中的每个条目格式化为文本。

**注意：**

这是一种便于快速存储阵列数据的功能。有关字节序和精度的信息会丢失，因此对于要在具有不同字节序的计算机之间存档数据或传输数据的文件，此方法不是一个好的选择。通过以速度和文件大小为代价输出数据作为文本文件，可以克服其中一些问题。

当fid是文件对象时，数组内容将直接写入文件，绕过文件对象的write方法。因此，tofile不能与支持压缩的文件对象（例如，GzipFile）或不支持的文件类对象fileno()（例如，BytesIO）一起使用。

# numpy.ndarray.tolist
`ndarray.tolist()`

将数组作为（可能是嵌套的）列表返回。

将数组数据的副本作为（嵌套的）Python列表返回。数据项将转换为最接近的兼容Python类型。

## Parameters:	
none

## Returns:	
y : list

可能嵌套的数组元素列表。

## Notes

可以重新创建阵列。`a = np.array(a.tolist())`

## 示例

In [36]:
>>> a = np.array([1, 2])
>>> a.tolist()

[1, 2]

In [37]:
>>> a = np.array([[1, 2], [3, 4]])
>>> list(a)

[array([1, 2]), array([3, 4])]

In [38]:
>>> a.tolist()

[[1, 2], [3, 4]]