NumPy术语表
====
Glossary
----

In [192]:
import numpy as np

# along an axis

轴是为具有多个维度的数组定义的。一个二维数组有两个对应的轴：第一个垂直向下跨行（axis 0），第二个是水平跨列运行（axis 1）。

许多操作都可以沿着这些轴进行。例如，我们可以对数组的每一行求和，在这种情况下，我们沿着列，或者`axis 1`：

In [193]:
>>> x = np.arange(12).reshape((3,4))

In [194]:
>>> x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [195]:
>>> x.sum(axis=1) #沿第2个轴（axis = 1)，跨列，求每行的和。

array([ 6, 22, 38])

In [196]:
x.sum(axis=0) #沿第1个轴（axis = 0)，跨行，求每列的和。

array([12, 15, 18, 21])

## 维数>2的数组

In [197]:
x = np.arange(24).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

对于维度>2的多维数组，求和输出结果数组的shape由其它轴的维数组成。

In [198]:
x.sum(axis=0) 
# 沿第1个轴axis=0，该轴有两个(3,4)的子数组，实际就是该轴上子数组的对应元素求和，返回一个(3,4)的数组

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [199]:
x.sum(axis=1) 
# 沿第2个轴，axis=1，轴是列就跨列，求每行的和，得到一个（2，4）的数组

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [200]:
x.sum(axis=2) # 沿第3个轴，axis=2,轴是行就跨行，求每列的和，得到一个（2，3）的数组

array([[ 6, 22, 38],
       [54, 70, 86]])

# array
一种同类数字元素的容器。数组中的每个元素占用固定大小的内存（因此是同类的），并且可以是单个类型的数字元素（例如float，int或complex）或组合（例如（float，int，float））。 每个数组都有一个关联的数据类型（或dtype），它描述了其元素的数字类型：

In [201]:
>>> x = np.array([1, 2, 3], float)

In [202]:
>>> x

array([1., 2., 3.])

In [203]:
>>> x.dtype 
# floating point number, 64 bits of memory per element
# More complicated data type: each array element is a combination of
# and integer and a floating point number

dtype('float64')

In [204]:
>>> np.array([(1, 2.0), (3, 4.0)], dtype=[('x', int), ('y', float)])

array([(1, 2.), (3, 4.)], dtype=[('x', '<i4'), ('y', '<f8')])

快速的元素级操作，称为`ufunc`，在数组上操作。

# array_like
任何可以被解释为ndarray的序列。这包括嵌套列表、元组、标量和现有数组。

# attribute
可以使用`obj.attribute`访问的对象的属性，例如，shape是数组的属性：

In [205]:
>>> x = np.array([1, 2, 3])
>>> x.shape

(3,)

# big-endian
当将多字节值作为字节序列存储在存储器中时，该序列首先寻址/发送/存储最高有效字节（最低地址）和最后有效字节（最高地址）。 常见于微处理器，用于通过网络协议传输数据。

# BLAS
[Basic Linear Algebra Subprograms，基本线性代数子程序](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms)

# broadcast
NumPy可以对形状不匹配的数组进行操作：(但必须是可广播的).

In [206]:
>>> x = np.array([1, 2])
>>> y = np.array([[3], [4]])
>>> x

array([1, 2])

In [207]:
>>> y

array([[3],
       [4]])

In [208]:
>>> x + y

array([[4, 5],
       [5, 6]])

See `numpy.doc.broadcasting` for more information.

# C order
参见后面的：`row-major`

# column-major

一种在一维计算机存储器中表示N维数组中的项的方法。在`column-major`列优先的顺序中，最左边的索引“变化最快”：例如数组：

```
[[1, 2, 3],
 [4, 5, 6]]
 ```
以column-major顺序的表示是：`[1, 4, 2, 5, 3, 6]`。即一列一列地排序。

column-major顺序也称为Fortran顺序，因为Fortran编程语言使用它。

## decorator
装饰器

转换函数的运算符。例如，日志装饰器可以定义打印函数调试信息的方式：

In [209]:
def log(f):
    def new_logging_func(*args, **kwargs):
        print("Logging call with parameters:", args, kwargs)
        return f(*args, **kwargs)
    return new_logging_func

现在，我们定义一个函数，可以使用log函数装饰它：

In [210]:
@log
def add(a, b):
    return a + b

调用add函数，则会产生装饰后的输出：

In [211]:
>>> add(1, 2)

Logging call with parameters: (1, 2) {}


3

# dictionary
类似于语言词典，它提供了单词和描述之间的映射，Python字典是两个对象之间的映射：

In [212]:
>>> x = {1: 'one', 'two': [1, 2]}
x

{1: 'one', 'two': [1, 2]}

这里，x是将键映射到值的字典，在这种情况下，整数1到字符串“one”，字符串“two”到列表`[1,2]`。 可以使用相应的键访问这些值：

In [213]:
x[1]

'one'

In [214]:
x['two']

[1, 2]

请注意，字典不以任何特定顺序存储。 此外，大多数mutable可变（参见下面的immutable不可变）对象（例如列表）不能用作键。

# field

在结构化数据类型中，每个子类型称为字段field。 该字段具有name（字符串），type（任何有效的dtype和可选的title。参阅 Data type objects (dtype).

# Fortran order
See column-major

# flattened
压缩成一维数组。 有关详细信息，请参阅`numpy.ndarray.flatten`。

## numpy.ndarray.flatten
`ndarray.flatten(order='C')`

返回一个数组的压缩成一维数组的副本。

### Parameters:
**order :** {‘C’, ‘F’, ‘A’, ‘K’}, 可选参数。

'C'表示以行为主（C风格）顺序展平。 'F'表示以列为主（Fortran风格）顺序展平。 如果a在内存中是是Fortran连续的，则'A'表示以列为主顺序展平，否则以行为主顺序。 'K'表示按元素在内存中出现的顺序展平。 默认值为“C”。

### Returns:	
y : ndarray

返回输入数组展平为一维数组的副本。

In [215]:
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()

array([1, 2, 3, 4])

In [216]:
>>> a.flatten('F')

array([1, 3, 2, 4])

# homogenous，

同质的，同类的

描述由块组成的存储器块，每个块由条目和相同大小组成，并且以完全相同的方式解释块。在最简单的情况下，每个块包含一个条目，例如int32或float64。

# immutable 不可变的

执行后无法修改的对象称为不可变。 两个常见的例子是字符串和元组。

# instance

类定义给出了构造对象的蓝本：
```
>>> class House(object):
...     wall_colour = 'white'
```
然而，我们必须在它存在之前建造一所房子：

`>>> h = House() # build a house`

现在，h被称为House实例。 因此，实例是类的特定实现。

# iterable
允许在项目上“行走”（迭代）的序列，通常使用如下循环：

In [217]:
>>> x = [1, 2, 3]
>>> [item**2 for item in x]

[1, 4, 9]

它经常与枚举结合使用：

In [218]:
keys = ['a','b','c']
for n, k in enumerate(keys):
    print("Key %d: %s" % (n, k))

Key 0: a
Key 1: b
Key 2: c


# list

一个Python容器，可以容纳任意数量的对象或条目。这些条目不必是同一类型，甚至条目本身也是lists：

In [219]:
>>> x = [2, 2.0, "two", [2, 2.0]]

list x 包含4个条目，每一个都可以被单独地访问：

In [220]:
>>> x[2] # the string 'two'

'two'

In [221]:
>>> x[3] # a list, containing an integer 2 and a float 2.0

[2, 2.0]

还可以使用切片一次访问多个条目：

In [222]:
>>> x[0:2] # or, equivalently, x[:2]

[2, 2.0]

在代码中，数组经常被方便地用一个嵌套的列表表示：

In [223]:
>>> np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

# little-endian

endian，字节存储次序，元组排列顺序。little-endian,一种存放二元化资料的格式（所有数字的低位组放在最前面）；

当将多字节值作为字节序列存储在存储器中时，该序列首先寻址/发送/存储最低有效字节（最低地址）和最后有效字节（最高地址）。在x86处理器中很常见。

# mask

一个布尔数组，用于为操作选择特定的元素：

In [224]:
>>> x = np.arange(5)
>>> x

array([0, 1, 2, 3, 4])

In [225]:
mask = (x>2)
mask

array([False, False, False,  True,  True])

In [226]:
x[mask]

array([3, 4])

In [227]:
x[mask]=-1
x

array([ 0,  1,  2, -1, -1])

# masked array

掩码数组，由掩码(mask)标示的值组成的数组：

In [228]:
>>> x = np.ma.masked_array([np.nan, 2, np.nan], [True, False, True])
>>> x

masked_array(data=[--, 2.0, --],
             mask=[ True, False,  True],
       fill_value=1e+20)

In [229]:
 x + [1, 2, 3]

masked_array(data=[--, 4.0, --],
             mask=[ True, False,  True],
       fill_value=1e+20)

在包含缺失或无效条目的数组上操作时，通常会使用掩码数组。

## 掩码数组详解

数据在多数情况下是凌乱的，并且含有空白的或者无法处理的字符，掩码数组可以很好的忽略残缺的或者是无效的数据点。

掩码数组由一个正常数组与一个布尔数组组成，若布尔数组中为Ture，则表示正常数组中对应下标的值无效，反之False表示对应正常数组的值有效。

numpy.ma模块中提供掩码数组的处理，这个模块中几乎完整复制了numpy中的所有函数，并提供掩码数组的功能：

In [230]:
import numpy.ma as ma
x = np.array([1,2,3,5,7,4,3,2,8,0])
x

array([1, 2, 3, 5, 7, 4, 3, 2, 8, 0])

In [231]:
mask = x < 5
mx = ma.array(x,mask=mask)
mask

array([ True,  True,  True, False, False,  True,  True,  True, False,
        True])

In [232]:
mx

masked_array(data=[--, --, --, 5, 7, --, --, --, 8, --],
             mask=[ True,  True,  True, False, False,  True,  True,  True,
                   False,  True],
       fill_value=999999)

掩码数组具有三个属性：data、mask、fill_value； 
- data表示原始数值数组， 
- mask表示获得掩码用的布尔数组， 
- fill_value表示的填充值替代无效值之后的数组，该数组通过filled()方法查看；

掩码数组可以使用各种下标对象对其进行存取，在被掩码部分值为masked，可以设置某个位置值为ma.masked，使其被掩而失效；

In [233]:
mx[3]

5

In [234]:
mx[3]=ma.masked #设置mx[3]=ma.masked，使得该位置的值失效
mx

masked_array(data=[--, --, --, --, 7, --, --, --, 8, --],
             mask=[ True,  True,  True,  True, False,  True,  True,  True,
                   False,  True],
       fill_value=999999)

# matrix

二维 ndarray，在整个操作过程中保持其二维特性。 它有一些特殊的操作，如`*`（矩阵乘法）和`**`（矩阵幂），定义如下：

In [235]:
>>> x = np.mat([[1, 2], [3, 4]])
>>> x

matrix([[1, 2],
        [3, 4]])

In [236]:
x*2

matrix([[2, 4],
        [6, 8]])

In [237]:
x

matrix([[1, 2],
        [3, 4]])

In [238]:
x**2

matrix([[ 7, 10],
        [15, 22]])

# method

与对象相关联的函数。例如，每个ndarray都有一个叫做repeat的方法：

In [239]:
>>> x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [240]:
>>> x.repeat(2)

array([1, 1, 2, 2, 3, 3])

# ndarray
See array.

# record array

具有结构化数据类型的ndarray，其已被子类化为np.recarray，其dtype的类型为np.record，使得其数据类型的字段可通过属性访问。

# reference

如果a是对b的引用，则`（a is b）== True`。 因此，a和b是同一Python对象的不同名称。

# row-major

一种在一维计算机存储器中表示N维数组中的项的方法。 在行主要顺序中，最右边的索引“变化最快”，例如数组：
```
[[1, 2, 3],
 [4, 5, 6]]
 ```

以行为主的顺序表示就是：`[1, 2, 3, 4, 5, 6]`

行为主的顺序也称为C顺序，因为C编程语言使用它。 默认情况下，新的NumPy数组按行为主顺序排列。

# self

通常在方法签名中看到，self指的是关联类的实例。 例如：

In [241]:
class Paintbrush(object):
    color = 'blue'
    def paint(self): #方法以self为参数
        print("Painting the city %s!" % self.color)

In [242]:
p = Paintbrush() #p是类的一个实例
p.color = 'red' #实例的color属性被设置为'red'
p.paint() # self refers to 'p' #调用p实例的paint()方法

Painting the city red!


# slice

切片，用于从一个序列中选择特定的元素：

In [243]:
>>> x = range(5)
>>> x

range(0, 5)

In [244]:
>>> x[1:3] # slice from 1 to 3 (excluding 3 itself)

range(1, 3)

In [245]:
>>> x[1:5:2] # slice from 1 to 5, but skipping every second element

range(1, 5, 2)

In [246]:
>>> x[::-1] # slice a sequence in reverse

range(4, -1, -1)

数组可能有多个维度，每个维度都可以单独切片：

In [247]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [248]:
x[:,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

# structure
See structured data type

# structured data type

由其它数据类型组成的数据类型。

# tuple

一种可能包含各种类型的变量的序列。元组是不可变的，也就是说一旦建造，就不能改变。类似于列表，它可以被索引和切片：

In [249]:
>>> x = (1, 'one', [1, 2])
>>> x

(1, 'one', [1, 2])

In [250]:
>>> x[0]

1

In [251]:
>>> x[:2]

(1, 'one')

一个有用的概念是“元组解包”，它允许将变量分配给元组的内容：

In [252]:
>>> x, y = (1, 'two')

In [253]:
x

1

In [254]:
y

'two'

当函数返回多个值时，通常会使用这种方法：

In [255]:
def return_many():
    return 1, 'alpha', 'End'

In [256]:
a, b, c = return_many()

In [257]:
a

1

In [258]:
b

'alpha'

In [259]:
c

'End'

# ufunc

通用函数。 快速元素方式的数组操作。例如 add，sin 和 logical_or。

# view

一个不拥有自己数据的数组，而是指向另一个数组的数据。 例如，我们可以创建视图，它仅显示另一个数组的每个第二个元素：
An array that does not own its data, but refers to another array’s data instead. For example, we may create a view that only shows every second element of another array:

In [260]:
>>> x = np.arange(5)
>>> x

array([0, 1, 2, 3, 4])

In [261]:
>>> y = x[::2]
>>> y

array([0, 2, 4])

In [262]:
>>> x[0] = 3 # changing x changes y as well, since y is a view on x
>>> y

array([3, 2, 4])

# wrapper 封装

Python是一种高级（高度抽象或类似英语）的语言。 这种抽象是以执行速度为代价的，有时需要使用较低级别的语言来进行快速计算。 包装器是在高级语言和低级语言之间提供桥接的代码，例如允许Python执行用C或Fortran编写的代码。

例如，ctypes，SWIG 和 Cython（封装 C 和 C ++）和 f2py（封装 Fortran）等。