# np.frombuffer 的 AttributeError

```
In [62]: np.frombuffer('hello world')

AttributeError: 'str' object has no attribute '__buffer__'

In [63]: np.frombuffer(b'hello world')

ValueError: buffer size must be a multiple of element size

In [64]: np.frombuffer(b'hello world',dtype='S1')
Out[64]: 
array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l', b'd'],  dtype='|S1')
```

In PY3, the default string type is unicode. The b is used to create and display bytestrings.

**The np.frombuffer docs should be updated to reflect the difference. The 'hello world' example only works with PY2 or with PY3 bytestrings.**

**As I noted in the comments, there are few SO questions regarding frombuffer, indicating that it is rarely used.  np.array is by far the most common way of making an array, even from strings:**

**应更新np.frombuffer文档以反映差异。 'hello world'示例仅适用于PY2或PY3字节串。**

**正如我在评论中所指出的，关于frombuffer的SO问题很少，表明它很少被使用。 到目前为止，np.array是制作数组的最常用方法，即使是字符串：**

```

In [80]: np.array('hello')
Out[80]: 
array('hello', 
      dtype='<U5')
or use list to split the string into characters:

In [81]: np.array(list('hello'))
Out[81]: 
array(['h', 'e', 'l', 'l', 'o'], 
      dtype='<U1')

In [82]: np.array(b'hello')
Out[82]: 
array(b'hello', 
      dtype='|S5')
In [83]: np.array(list(b'hello'))
Out[83]: array([104, 101, 108, 108, 111])

In [85]: np.fromiter('hello','S1')
Out[85]: 
array([b'h', b'e', b'l', b'l', b'o'], 
      dtype='|S1')
In [86]: np.fromiter('hello','U1')
Out[86]: 
array(['h', 'e', 'l', 'l', 'o'], 
      dtype='<U1')*
```

In [4]:
import numpy as np
np.array('hello')

array('hello',
      dtype='<U5')

In [5]:
np.frombuffer(b'\x01\x02', dtype=np.uint8)

array([1, 2], dtype=uint8)

In [6]:
 np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8, count=3)

array([1, 2, 3], dtype=uint8)