13-数组的索引基础
====
 indexing basic
 ----
 NumPy User Guide ---> NumPy basics

数组索引是指使用方括号（[ ]）来索引数组的值。索引有很多选项，它可以为numpy索引提供强大的功能，但是强大的功能也会带来一些复杂性和混淆的可能性。 我们先仅概述与索引相关的各种选项和问题。 关于索引的详细讨论请参见Indexing routines。

# 赋值和引用

以下大多数示例展示了使用索引引用数组中的数据。在赋值给数组时，这些示例也可以正常工作。有关赋值如何工作的具体示例和说明，请参见最后一节。

# 单元素的索引

人们期望一维数组的单元素索引。它的工作方式与其他标准Python序列完全相同。它从0开始，并接受负索引从数组末尾开始索引。

正索引从0开始，负索引从-1开始。

In [2]:
import numpy as np
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[2]

2

In [4]:
x[-2]

8

与列表和元组不同，numpy数组支持多维数组的多维索引。这意味着没有必要将每个维度的索引分开放到它们自己的方括号集里。

In [5]:
>>> x.shape = (2,5) # now x is 2-dimensional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
>>> x[1,3]

8

In [7]:
>>> x[1,-1]

9

**请注意**，如果用比维度少的索引检索多维数组，则得到一个子维度数组。 例如：

In [8]:
x[0]

array([0, 1, 2, 3, 4])

也就是说，指定的每个索引选择与所选维度的其余部分对应的数组。 在上面的示例中，选择0表示长度为5的剩余维度未指定，返回的是该维度和大小的数组。 必须注意的是，返回的数组不是原始数据的副本，而是指向内存中与原始数组相同的值。 在这种情况下，返回第一个位置（0）的 1-D array。 因此，在返回的数组上使用单个索引会进一步返回单个元素。示例如下：

In [9]:
x[0][2]

2

请**注意**虽然 `x [0,2] = x [0] [2]`，但是，因为在第一个索引之后再用 2 对其索引创建了一个新的临时数组，所以第二种情况效率更低。

请注意那些习惯于 IDL 或 Fortran 内存顺序的内容，因为它与索引有关。 NumPy 使用 C 顺序索引。这意味着最后一个索引通常代表最快速变化的内存位置，与 Fortran 或 IDL 不同，IDL 或 Fortran 顺序中第一个索引代表内存中变化最快的位置。这种差异代表了混淆的巨大潜力。

# 其它索引选项

Other indexing options

可以对数组进行切片(slice)和跨步(stride)以提取具有相同维度数但尺寸与原始数组不同的数组。切片和跨步的工作原理与列表和元组完全相同，只是它们还可以用于多个维度。用例子说明是最好的：

In [10]:
>>> x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
>>> x[2:5]

array([2, 3, 4])

In [12]:
>>> x[:-7]

array([0, 1, 2])

In [13]:
>>> x[1:7:2]

array([1, 3, 5])

In [14]:
>>> y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [15]:
>>> y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

请注意，数组切片不会复制内部数组数据，但会生成原始数据的新视图。

可以使用其他数组索引数组，以便从数组中选择值列表到新数组中。有两种不同的方法来实现这一点。 

**一是** 使用一个或多个索引值数组。

**二是** 给出一个正确形状的布尔数组来指示要选择的值。

索引数组是一个非常强大的工具，可以避免循环遍历数组中的各个元素，从而大大提高性能。

可以使用特殊功能通过索引有效地增加数组中的维数，以便生成的数组获取在表达式或特定函数中使用所需的形状。

# 索引数组

NumPy数组可以使用其他数组（或任何其他可以转换为数组的类似序列的对象，如列表，但元组除外）作为索引数组来检索数据。索引数组的使用范围从简单、直接的案例到复杂的、难以理解的案例。对于索引数组的所有情况，返回的是原始数据的副本，而不是切片获取的视图。

索引数组必须是整数类型。数组中的每个值指示要使用的数组中的哪个值代替索引值。 示例说明：

## indexes和indices的区别

中文的“索引”一词，有两个含义：
- 一是“索引标记值”，从数据块（数组，矩阵，集合，列表等）中检索数据的位置，比如，列表的0位，3位，-1位等；
- 二是“检索出”，意思是从数据块中检索数据的动作。

在英文中常用两个单词表达“索引”，index，indices

**index** `/'ɪndeks/ ` 简明含义如下：
- n. 指标；<数>指数；索引；指针
- vi. 做索引
- vt. 指出；给…编索引；把…编入索引
- 名词复数 indexes或indices
- 动词，第三人称单数：indexes；过去分词：indexed；现在进行时：indexing；过去式：indexed

**indexes**`/'indeksis/ `
- n. 指数；标准（index的复数）；索引
- v. 表明（index的第三人称单数）；指示；为…编索引

*一般认为两者基本相同，细微的区别在于：*
- indexes在美国、加拿大等国的英语里比较常见。但indices盛行于除北美国家以外的英语里。
- indices一般在数学，金融和相关领域使用，而indexes使用则相对广泛。

在Python数据科学中会经常涉及到这两个词，甚至在一个句子中同时出现这两个词，可以这样区分理解它们：
1. indexing, indexed，显然都是动词形式，理解为从数据块中检索出数据；
2. indexes，看它在句子中的词性，如果是动词的第三人称单数形式，含义同上；如果是名词复数，就是“索引”值；
3. indices，如果是名词，就是index的复数，意指有多个“索引”值；如果是第三人称单数，就是动词，就是“检索”。


比如下面这段话：
Array indexing（动名词，理解为“检索”） refers to any use of the square brackets ([]) to index（to 动词原型，也理解为“检索”） array values. There are many options to indexing（检索）, which give numpy indexing（检索） great power, but with power comes some complexity and the potential for confusion. This section is just an overview of the various options and issues related to indexing. Aside from single element indexing, the details on most of these options are to be found in related sections.

这段话翻译如下就较易理解：

“数组检索是指使用方括号（[]）来检索数组的值。检索有很多选项（选项就是“检索”动作的方式），它可以为 numpy 的数据检索提供强大的功能，但是强大功能会带来一些复杂性和混淆的可能性。 本节仅概述与检索相关的各种选项和问题。除了检索单元素外，大多数这些选项的详细信息都可以在相关章节中找到。”

显然，将indexing翻译为“检索”比翻译为“索引”更易于理解。

**再比如：**
“NumPy arrays may be indexed（过去分词，“检索”） with other arrays (or any other sequence- like object that can be converted to an array, such as lists, with the exception of tuples; see the end of this document for why this is). The use of index（名词，“索引”） arrays ranges from simple, straightforward cases to complex, hard-to-understand cases. For all cases of index arrays, what is returned is a copy of the original data, not a view as one gets for slices.”

NumPy数组可以使用其他数组（或任何其他可以转换为数组的类似序列的对象，如列表，但元组除外）作为索引数组来检索数据。索引数组的使用范围从简单、直接的案例到复杂的、难以理解的案例。对于索引数组的所有情况，返回的是原始数据的副本，而不是切片获取的视图。

上文中“index arrays”是指用数组（甚至可能是多个数组）作为“索引值”。

In [16]:
>>> x = np.arange(10,1,-1)
>>> x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [17]:
>>> x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

由值3,3,1和8组成的索引数组相应地创建一个长度为4的数组（与索引数组相同），其中每个索引值由索引数组在被检索数组中所具有的值替换。

允许使用负值，并且与单个索引或切片一样工作：

In [18]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

索引值超出了边界会触发一个错误：

In [19]:
>>> x[np.array([3, 3, 20, 8])]

IndexError: index 20 is out of bounds for axis 0 with size 9

一般来说，使用索引数组时返回的是与索引数组具有相同形状的数组，但类型和值是被检索数组的。可以使用多维索引数组更能说明问题：

In [ ]:
>>> x[np.array([[1,1],[2,3]])]

# 检索多维数组
Indexing Multi-dimensional arrays

当检索多维数组时，事情变得更加复杂，尤其是使用“多维索引数组”检索“多维数组”。这些往往是更不寻常的用途，但它们是允许的，它们对某些问题很有用。我们从最简单的多维情况开始（使用前面示例中的数组y）：

In [ ]:
y

In [ ]:
>>> y[np.array([0,2,4]), np.array([0,1,2])]

在这种情况下，如果索引数组具有匹配的形状，并且被检索数组的每个维度都有一个索引数组，则结果数组具有与索引数组相同的形状，值对应于索引数组中每个位置的索引集。在此示例中，两个索引数组的第一个索引值均为0，因此结果数组的第一个值为y [0,0]。 下一个值是y [2,1]，最后一个是y [4,2]。

**值对应于索引数组中每个位置的索引集。**这句话的意思是：
- 每个维度都有一个索引数组；
- 每个索引数组相同位置的索引值组成一个索引集；
- 用这个索引集在被检索数组中检索出数据；
- 检索出的数据用在输出数组的对应位置。

如果索引数组的形状不同，则尝试将它们广播为相同的形状。如果它们无法广播到相同的形状，则会引发异常：

In [ ]:
y[np.array([0,2,4]), np.array([0,1])]

广播机制允许索引数组与其他索引的标量组合。结果是标量值用于索引数组的所有相应值：

In [ ]:
 y[np.array([0,2,4]), 1]

跳到下一级别的复杂性，可以使用索引数组对数组进行部分检索。需要一些思考才能理解在这种情况下会发生什么。 例如，如果我们仅使用一个索引数组检索y：

In [ ]:
y

In [ ]:
 y[np.array([0,2,4])]

结果是构造一个新数组，其中索引数组的每个值从被检索的数组中选择一行，结果数组具有一定的形状（索引元素的数量就是结果数组的行数）。

这可能有用的示例是用于颜色查找表，其中我们想要将图像的值映射到 RGB 三元组以供显示。查找表可以具有形状（nlookup，3）。 使用带有dtype = np.uint8的形状（ny，nx）的图像检索此类数组（或任何整数类型，只要值与查找表的边界一致）将生成一个 shape 为（ny，nx， 3）的数组，其中三个 RGB 值与每个像素位置相关联。

通常，结果数组的形状是索引数组的形状（或所有索引数组被广播到的形状）与被检索数组中任何未使用的维度（未检索的维度）的形状的串联。

上例是2-D数组，行数是0维度，列数是1维度。只有一个索引数组，用于行维度，被检索数组未使用的维度就是列维度，结果数组的形状就是“索引数组”的行数和被检索数组的列数的串联，得到一个 3 * 7 的数组。

# Boolean 或 “mask" 索引数组

用作索引的布尔数组的处理方式与索引数组完全不同。布尔数组的 shape 必须与被检索的数组的初始维度相同。在最简单的情况下，布尔数组具有相同的形状：

In [ ]:
b = y>20

In [ ]:
b

In [ ]:
y[b]

与整数索引数组的情况不同，在布尔情况下，结果是一个一维数组，其中包含被检索数组中与布尔数组中所有 True 元素对应的所有元素。被检索数组中的元素总是被迭代，并以行优先（C样式）顺序返回。结果与`y [np.nonzero（b）]`相同。与索引数组一样，返回的是数据的副本，而不是切片所获得的视图。

**说明：**  row-major (C-style) 顺序，意思是一行一行地读取，读完一行再读取下一行。行优先，列坐标（最右边的索引）变化最快.

如果 y 比 b 有更多的维度，返回的结果将是多维的。例如：

In [ ]:
>>> b[:,5] 
# 使用一个1-D的布尔值，它的第一个 dim 与 y 的第一个dim一致。

"使用一个1-D的布尔值，它的第一个 dim 与 y 的第一个dim一致"。意思是：一维布尔索引数组的元素个数与被检索数组的shape(s0,s1,...sn)中的s0应该相等，否则会触发错误。实际就是布尔索引数组的元素个数与行数相等。

换一种方式可能更容易理解：检索时，按照行优先的原则，根据1-D的布尔数组，依次决定是否选择对应的行。因为只有一个索引数组，列维度与被检索数组相同，参见索引数组部分的“串联”。

In [ ]:
y

In [ ]:
>>> y[b[:,5]]

这里，第4行和第5行是从索引数组中选择的，与被检索数组的列“串联”成一个2-D数组。

通常，当布尔数组的维度小于被索引的数组时，这相当于y [b，...]，这意味着 y 被 b 后面跟随填充 y 的秩所需数量的“ ：”。 因此，结果的 shape 有一个维度包含布尔数组的 True 元素的数量，后跟被索引数组的剩余维度。

例如，有一个shape为(2,3,2,4)的被检索数组：

In [60]:
>>> x = np.arange(48).reshape(2,3,2,4)
>>> x

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39]],

        [[40, 41, 42, 43],
         [44, 45, 46, 47]]]])

使用具有四个 True 元素的 shape（2,3）的二维布尔数组从中检索数据，

In [77]:
c=np.array([[False, True,True],[True, True,False]])
c.shape

(2, 3)

In [78]:
x[c]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [76]:
x[c].shape

(4, 2, 4)

得到的是一个shape(4,2,4)的三维数组，第一个维度是True的数量 4，被检索数组是 4-D，索引数组是2-D，剩余的还有2-D，即（2，3）后面的（2，4）。True的数量 4 与剩余 （2，4）串联组成输出数组的shape，即为（4，2，4）。

如果使用有7个True，shape(2,3,2)的三维数组从中检索，应该得到shape(7,4)的数组。7为True的数量，剩余的维度是shape(4)，两者串联得到：

In [82]:
>>> b = np.array([[[False, False],[True, True],[True, False]],
                [[False, False], [True, True],[True, True]]])
>>> b.shape

(2, 3, 2)

In [83]:
>>> x[b]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [81]:
x[b].shape

(7, 4)

**说明：**
- 索引数组的shape与被检索数组的shape从左到右依次匹配，否则将触发错误。上例中，被检索数组的shape(2,3,2,4)，索引数组的shape必须是（2），（2，3），（2，3，2），（2，3，2，4）;
- 得到的数组，“维度数 = （被检索数组维度 - 索引数组的维度 + 1）”;
- 得到的数组的shape由索引数组的True数量与被检索数组剩余维组成。

In [93]:
d = np.array([False, True])
d.shape

(2,)

In [94]:
x[d]

array([[[[24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39]],

        [[40, 41, 42, 43],
         [44, 45, 46, 47]]]])

In [95]:
x[d].shape

(1, 3, 2, 4)

# 结合索引数组与切片
Combining index arrays with slices

索引数组可以与切片结合使用：

In [96]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

实际上，切片被转换为索引数组 `np.array（[[1,2]]）`（shape（1,2）），它与索引数组一起广播以产生shape(3,2)的结果数组。

同样，切片可以与广播的布尔索引组合：

In [99]:
b = y>20
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

# 结构化检索工具
Structural indexing tools

为了便于数组形状与表达式和赋值的轻松匹配，可以使用`np.newaxis`对象在数组索引中添加大小为1的新维度。例如：

In [100]:
>>> y.shape

(5, 7)

In [101]:
>>> y[:,np.newaxis,:].shape

(5, 1, 7)

请注意，数组中没有新元素，只是增加了维度。这可以方便地以一种方式组合两个数组，否则将需要显式重塑(reshape)操作。 例如：

In [102]:
>>> x = np.arange(5)
>>> x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [103]:
x

array([0, 1, 2, 3, 4])

In [105]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [106]:
x.reshape(5,1)+x.reshape(1,5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

省略号语法可用于指示选择整体中所有剩余的未指定维度。例如：

In [110]:
 z = np.arange(81).reshape(3,3,3,3)
 z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [ ]:
 z[1,...,2]

这与下面的索引等效：

In [108]:
>>> z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

# 为被检索数组赋值
Assigning values to indexed arrays

如上所述，可以选择一个数组的子集分配给使用单个索引、切片、index和mask数组。分配给索引数组的值必须形状一致（相同的shape或广播到索引的形状）。例如，允许为切片分配一个常量：

In [114]:
x = np.arange(10)
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [116]:
x[2:7] = np.arange(5)

array([0, 1, 2, 3, 4])

请注意，如果将较高类型分配给较低类型（例如浮点数到整数）则赋值结果可能会改变，甚至触发异常（将复数分配给浮点数或整数）：

In [117]:
>>> x[1] = 1.2
>>> x[1]

1

In [118]:
>>> x[1] = 1.2j

TypeError: can't convert complex to int

与某些引用（例如数组和掩码索引）不同，总是对数组中的原始数据进行赋值（实际上，没有什么意义！）。 但请注意，某些操作可能无法正常工作。下面这个特殊的例子通常让人惊讶：

In [119]:
>>> x = np.arange(0, 50, 10)
>>> x

array([ 0, 10, 20, 30, 40])

In [120]:
>>> x[np.array([1, 1, 3, 1])] += 1
>>> x

array([ 0, 11, 20, 31, 40])

人们期望第一个位置将增加 3. 实际上，它只会增加 1。原因是从原始（作为临时）提取的新数组包含值1,1,3,1，然后将值1添加到临时值，然后将临时值分配回原始数组。 因此，数组在`x [1] +1` 处的值被分配给 `x [1]` 三次，而不是递增 3 次。

# 处理程序中可变数量的索引
Dealing with variable numbers of indices within programs

索引语法非常强大，但在处理可变数量的索引时会受到限制。例如，如果您想编写一个可以处理具有不同维数的参数的函数，而不必为每个可能的维度编写特殊情形的代码，那么该怎么做呢？ 如果向索引提供元组，则元组将被解释为索引列表。 例如（使用先前的数组z定义）：

In [121]:
>>> indices = (1,1,1,1)
>>> z[indices]

40

因此，可以使用代码构造任意数量的索引的元组，然后在索引中使用它们。

可以使用Python中的slice（）函数在程序中指定切片。 例如：

In [123]:
>>> indices = (1,1,1,slice(0,2)) # same as [1,1,1,0:2]
>>> z[indices]

array([39, 40])

同样，省略可以通过使用 Ellipsis 对象来指定：

In [124]:
>>> indices = (1, Ellipsis, 1) # same as [1,...,1]
>>> z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

由于这个原因，可以直接使用np.nonzero（）函数的输出作为索引，因为它总是返回索引数组的元组。

因为对元组的特殊处理，它们不会像列表那样自动转换为数组。 举个例子：

In [125]:
>>> z[[1,1,1,1]] # produces a large array

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [126]:
>>> z[(1,1,1,1)] # returns a single value

40