11-创建数组的程序之六
====
Building matrices
----

| Building   matrices        |                                                              |
| -------------------------- | ------------------------------------------------------------ |
| diag(v[, k])               | Extract a   diagonal or construct a diagonal array.          |
| diagflat(v[, k])           | Create   a two-dimensional array with the flattened input as a diagonal. |
| tri(N[, M, k, dtype])      | An   array with ones at and below the given diagonal and zeros elsewhere. |
| tril(m[, k])               | Lower   triangle of an array.                                |
| triu(m[, k])               | Upper   triangle of an array.                                |
| vander(x[, N, increasing]) | Generate   a Vandermonde matrix.                             |

# numpy.diag
`numpy.diag(v, k=0)`

提取一个对角线或构造一个对角线数组。

如果你使用这个函数来提取一个对角线，并希望对结果数组进行写入，参见 numpy 的更详细的文档。;它是返回一个副本，还是返回一个视图取决于您所使用的numpy版本。

## Parameters:	
**v :** array_like
如果 v 是一个2-D数组，返回第 k 个对角线的副本。如果 v 是一个1-D数组，返回一个 2-D 数组，v 在第 k 个对角线上。

**k :** int, 可选关键字参数。对角线问题。默认是0。在主对角线上面的对角线使用 k > 0，在主对角线下面的对角线使用 k < 0.

## Returns:	
out : ndarray

提取对角线或者构造对角线数组。

## 示例

In [5]:
import numpy as np
>>> x = np.arange(9).reshape((3,3))
>>> x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
>>> np.diag(x)

array([0, 4, 8])

In [10]:
>>> np.diag(x, k=1)

array([1, 5])

In [8]:
>>> np.diag(x, k=-1)

array([3, 7])

In [9]:
>>> np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

# numpy.diagflat
`numpy.diagflat(v, k=0)`

创建一个2维数组，用展平的输入作为对角线。

## Parameters:	
**v :** array_like

输入数据，它被展平，并被设置为输出的第 k 条对角线。

**k :** int, 可选关键字参数。对角线设置；0，默认的，对应于主对角线，一个正的（负的） k 给出了在主对角线上面（下面）的对角线。

## Returns:	

out : ndarray，输出2-D数组。

## 示例

In [16]:
>>> np.diagflat([[1,2,3], [3,4,5]])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [17]:
>>> np.diagflat([1,2,3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

# numpy.tri
`numpy.tri(N, M=None, k=0, dtype=<class 'float'>)`

一个数组，其中包含给定对角线和低于给定对角线的数字，其他地方为零。

## Parameters:	
**N :** int，数组的行数。

**M :** int, 可选关键字参数。数组的列数。默认 M 等于 N.

**k :** int, 可选关键字参数。子对角线及其下面的对角线被填充。k = 0是主对角线，k < 0在主对角线下面，K > 0在主对角线上面。默认是 0。

**dtype :** dtype, 可选关键字参数。返回数组的数据类型。默认是float。

## Returns:	
tri : ndarray of shape (N, M)

shape为(N, M)的 ndarray。

数组的下三角形填充1，其他地方为零; 也就是说，对于i <= j + k，T [i，j] == 1，否则为0。

## 示例

In [21]:
>>> np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [20]:
>>> np.tri(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

# numpy.tril
`numpy.tril(m, k=0)`

一个数组的下三角。

返回数组的副本，其中第k个对角线以上的元素归零。

## Parameters:	
**m :** array_like, shape (M, N)，输入数组。

**k :** int, 可选关键字参数。在对角线以上的元素转换为0。 k = 0 (默认) 是主对角线，k < 0 在主对角线下面，k > 0 在主对角线上面。

## Returns:	
tril : ndarray, shape (M, N)

m的下三角形，具有与m相同的形状和数据类型。

## 示例

In [22]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

# numpy.triu
`numpy.triu(m, k=0)`

数组的上三角形。

返回matrix的一个副本，第k对角线下方的元素归零。

## 示例

In [23]:
 np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# numpy.vander
`numpy.vander(x, N=None, increasing=False)`

生成一个Vandermonde矩阵。范德蒙矩阵是法国数学家范德蒙(Vandermonde,AlexandreTheophile, 1735～1796) 提出的一种各列为几何级数的矩阵。

输出矩阵的列是输入向量的幂（powers）。 幂的顺序由 increasing 布尔参数决定。 具体地，当 increasing 为 False 时，第 i 个输出列是输入向量元素提升到 ‘N - i - 1’的幂。这种每行中具有几何级数的矩阵以 Alexandre-Theophile Vandermonde 命名。

## Parameters:	
**x :** array_like，1-D输入数组。

**N :** int, 可选关键字参数。输出中的列数。 如果未指定N，则返回正方形数组 (N = len(x)).

**increasing :** bool, 可选关键字参数。列的幂顺序。如果是True，幂从左到右增加，如果为False（默认）则是相反的。

## Returns:	
out : ndarray

Vandermonde matrix. 如果 increasing 是 False, 第一列是 x^(N-1)，第二列是x^(N-2)， 等等。如果increasing是True，列是x^0, x^1, ..., x^(N-1).

## 示例

In [24]:
>>> x = np.array([1, 2, 3, 5])
>>> N = 3
>>> np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [25]:
>>> np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [26]:
>>> x = np.array([1, 2, 3, 5])
>>> np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [27]:
>>> np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

方形Vandermonde矩阵的行列式是两个输入向量值之间的差异的乘积：

In [28]:
>>> np.linalg.det(np.vander(x))

48.00000000000007

In [29]:
>>> (5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48