20-Input and Output
===

| Input   and Output |                                 |
| ------------------ | ------------------------------- |
| 1                  | NumPy binary   files (NPY, NPZ) |
| 2                  | Text files                      |
| 3                  | Raw binary   files              |
| 4                  | String   formatting             |
| 5                  | Memory mapping   files          |
| 6                  | Text   formatting options       |
| 7                  | Base-n   representations        |
| 8                  | Data sources                    |
| 9                  | Binary Format   Description     |



# NumPy binary files (NPY, NPZ)


| NumPy binary   files (NPY, NPZ)              |                                                              |
| -------------------------------------------- | ------------------------------------------------------------ |
|` load(file[, mmap_mode, allow_pickle, …])`     | Load   arrays or pickled objects from .npy, .npz or pickled files. |
| `save(file, arr[, allow_pickle, fix_imports])` | Save   an array to a binary file in NumPy .npy format.       |
| `savez(file, *args, **kwds)`                   | Save   several arrays into a single file in uncompressed .npzformat. |
|` savez_compressed(file, *args, **kwds)`        | Save   several arrays into a single file in compressed .npz format. |


# numpy.load
`numpy.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')`

从.npy，.npz或pickle文件加载数组或pickle对象。

## Parameters:	
**file** : file-like object, string, or pathlib.Path

类似文件对象，字符串，或者**pathlib.Path**

要读取的文件。 类文件对象必须支持seek（）和read（）方法。 pickle文件要求类文件对象也支持readline（）方法。

**mmap_mode** : `{None, ‘r+’, ‘r’, ‘w+’, ‘c’}`, optional

如果不是None，则使用给定模式对文件进行内存映射（有关模式的详细说明，请参阅`numpy.memmap`）。 内存映射阵列保留在磁盘上。 但是，它可以像任何ndarray一样访问和切片。 内存映射对于访问大型文件的小片段而不将整个文件读入内存特别有用。

**allow_pickle** : bool, optional

允许加载存储在npy文件中的pickled对象数组。禁止pickles的原因包括安全性，因为加载pickled数据可以执行任意代码。如果不允许使用pickle，则加载对象数组将失败。默认值：True

**fix_imports** : bool, optional

仅在 Python 3 上加载 Python 2 生成的 pickle 文件时才有用，其中包括包含对象数组的`npy / npz`文件。 如果`fix_imports`为 True，则 pickle 将尝试将旧的Python 2名称映射到Python 3中使用的新名称。

**encoding** : str, optional

读取Python 2字符串时要使用的编码。仅在Python 3中加载Python 2生成的pickle文件时才有用，其中包括包含对象数组的`npy / npz`文件。 不允许使用“latin1”，“ASCII”和“bytes”以外的值，因为它们可能会破坏数字数据。 默认值：'ASCII'.

## Returns:	
**result** : array, tuple, dict, etc.

数据存储在文件中。对于`.npz`文件，必须关闭返回的`NpzFile`类实例以避免泄漏文件描述符。

## Raises:	
**IOError** 如果输入文件不存在或无法读取。

**ValueError** 该文件包含一个对象数组，但给出了`allow_pickle = False`。

**注意**

- 如果文件包含pickle数据，则返回pickle中存储的任何对象。

- 如果文件是`a.npy`文件，则返回单个数组。

- 如果文件是`a.npz`文件，则返回类似字典的对象，其中包含`{filename：array}`键值对，一个用于存档中的每个文件。

- 如果文件是`a.npz`文件，则返回的值支持上下文管理器协议，其方式与open函数类似：

```
with load('foo.npz') as data:
    a = data['a']
```
退出'with'块时，底层文件描述符将关闭。

## 示例

将数据存储到磁盘，并再次加载：

In [2]:
import numpy as np

np.save('I:/tmp/123', np.array([[1, 2, 3], [4, 5, 6]]))
np.load('I:/tmp/123.npy')

array([[1, 2, 3],
       [4, 5, 6]])

将压缩数据存储到磁盘，然后再次加载：

In [3]:
>>> a=np.array([[1, 2, 3], [4, 5, 6]])
>>> b=np.array([1, 2])
>>> np.savez('/tmp/123.npz', a=a, b=b)
>>> data = np.load('/tmp/123.npz')
>>> data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
>>> data['b']

array([1, 2])

In [5]:
>>> data.close()

对存储的数组进行Mem-map，然后直接从磁盘访问第二行：

In [6]:
>>> X = np.load('/tmp/123.npy', mmap_mode='r')
>>> X[1, :]

memmap([4, 5, 6])

# numpy.save
`numpy.save(file, arr, allow_pickle=True, fix_imports=True)`

将数组保存为NumPy .npy格式的二进制文件。

## Parameters:	
**file** : file, str, or pathlib.Path

保存数据的文件或文件名。如果file是文件对象，则文件名不变。如果file是字符串或Path，则.npy 扩展名将附加到文件名（如果它还没有）。

**arr** : array_like，要保存的数组数据。

**allow_pickle** : bool, optional，

允许使用Python pickles保存对象数组。禁止 pickles 的原因包括安全性（加载 pickled 数据可以执行任意代码）和可移植性（pickled 对象可能无法在不同的Python安装上加载，例如，如果存储的对象需要不可用的库，并且并非所有的pickle数据都兼容Python 2和Python 3）。默认值：True

**fix_imports** : bool, optional

仅在强制Python 3上的对象数组中的对象以Python 2兼容的方式进行pickle时才有用。如果fix_imports为True，则pickle将尝试将新的Python 3名称映射到Python 2中使用的旧模块名称，以便使用Python 2可以读取pickle数据流。

## 示例

In [7]:
>>> from tempfile import TemporaryFile
>>> outfile = TemporaryFile()

>>> x = np.arange(10)
>>> np.save(outfile, x)

>>> outfile.seek(0) # Only needed here to simulate closing & reopening file
>>> np.load(outfile)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# numpy.savez

`numpy.savez(file, *args, **kwds)`

将多个数组以未压缩`.npz`格式保存到单个文件中。

如果传入的参数没有关键字，则`.npz`文件中的相应变量名称为`'arr_0'，'arr_1'`等。如果给出关键字参数，则`.npz` 文件中相应的变量名称将与关键字名称匹配。

## Parameters:	
**file** : str or file

文件名（字符串）或将保存数据的打开文件（类文件对象）。如果file是字符串或Path，则 .npz扩展名将附加到文件名（如果文件名尚不存在）。

**args** : Arguments, optional

要保存到文件的数组。由于Python无法知道外部数组的名称savez，因此将使用名称“arr_0”，“arr_1”等保存数组。这些参数可以是任何表达式。

**kwds** : Keyword arguments, optional

要保存到文件的数组。数组将使用关键字名称保存在文件中。

**Returns**: None

**注意：**

该`.npz`文件格式是它们所包含的变量命名的文件的压缩文档。存档未压缩，存档中的每个文件都包含一个`.npy`格式的变量。有关`.npy`格式的说明，请参阅numpy.lib.format。

当使用`load`打开保存的`.npz`文件时返回一个`NpzFile`对象。这是一个类似字典的对象，可以查询其数组列表（带有`.files`属性），也可以查询数组本身。

## 示例

In [8]:
>>> from tempfile import TemporaryFile
>>> outfile = TemporaryFile()
>>> x = np.arange(10)
>>> y = np.sin(x)

使用带 `*args*`的`savez`，使用默认的名字保存数组。

In [9]:
>>> np.savez(outfile, x, y)
>>> outfile.seek(0) # Only needed here to simulate closing & reopening file
>>> npzfile = np.load(outfile)
>>> npzfile.files

['arr_0', 'arr_1']

In [10]:
>>> npzfile['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

使用带`**kwds`参数的`savez`，用关键字参数命名保存的数组。

In [11]:
>>> outfile = TemporaryFile()
>>> np.savez(outfile, x=x, y=y)
>>> outfile.seek(0)
>>> npzfile = np.load(outfile)
>>> npzfile.files

['x', 'y']

In [12]:
>>> npzfile['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# numpy.savez_compressed
`numpy.savez_compressed(file, *args, **kwds)`

将多个数组以压缩`.npz`格式保存到单个文件中。

如果给出了关键字参数，则从关键字中获取文件名。如果传入的参数没有关键字，则存储的文件名为`arr_0，arr_1`等。

## Parameters:	
**file** : str or file

文件名（字符串）或将保存数据的打开的文件（类似文件的对象）。如果file是字符串或Path，则 `.npz`扩展名将附加到文件名（如果文件名尚不存在）。

**args** : Arguments, optional

要保存到文件的数组。由于Python无法知道外部数组的名称savez，因此将使用名称“arr_0”，“arr_1”等保存数组。这些参数可以是任何表达式。

**kwds** : Keyword arguments, optional

要保存到文件的数组。数组将使用关键字名称保存在文件中。

**Returns**: None

**注意：**

`.npz`文件格式是它们所包含的变量命名的文件的压缩文档。被压缩的存档带有`zipfile.ZIP_DEFLATED`，并且存档中的每个文件都包含一个`.npy`格式的变量。有关.npy格式的说明，请参阅 numpy.lib.format。

当用`load`打开保存的`.npz`返回一个NpzFile对象。这是一个类似字典的对象，可以查询其数组列表（带有`.files`属性），也可以查询数组本身。

## 示例

In [13]:
>>> test_array = np.random.rand(3, 2)
>>> test_vector = np.random.rand(4)
>>> np.savez_compressed('/tmp/123', a=test_array, b=test_vector)
>>> loaded = np.load('/tmp/123.npz')
>>> print(np.array_equal(test_array, loaded['a']))

True


In [14]:
>>> print(np.array_equal(test_vector, loaded['b']))

True
