25-Input and Output 之六
====
**Text formatting options**

| Text   formatting options                   |                                                              |
| ------------------------------------------- | ------------------------------------------------------------ |
| set_printoptions([precision, threshold, …]) | Set   printing options.                                      |
| get_printoptions()                          | Return   the current print options.                          |
| set_string_function(f[, repr])              | Set   a Python function to be used when pretty printing arrays. |
| printoptions(*args, **kwargs)               | Context   manager for setting print options.                 |

# numpy.set_printoptions
`numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, **kwarg)`

设置打印选项。

这些选项确定浮点数，数组和其他NumPy对象的显示方式。

Set printing options.

These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

## Parameters:	
**precision** : int or None, optional

浮点输出的精度位数（默认为8）。可能没有，如果floatmode不固定，打印尽可能多的数字所必需的唯一指定值。

Number of digits of precision for floating point output (default 8). May be None if floatmode is not fixed, to print as many digits as necessary to uniquely specify the value.

**threshold** : int, optional

触发汇总数组元素总数（默认为1000）,而不是全部的 repr。

Total number of array elements which trigger summarization rather than full repr (default 1000).

**edgeitems** : int, optional

每个维度开头和结尾的摘要中的数组项数（默认值为3）。

Number of array items in summary at beginning and end of each dimension (default 3).

**linewidth** : int, optional

每行的字符数，用于插入换行符（默认为75）。

The number of characters per line for the purpose of inserting line breaks (default 75).

**suppress** : bool, optional

如果为True，则始终使用固定点表示法打印浮点数，在这种情况下，当前精度中等于零的数字将打印为零。如果为假，则当最小数的绝对值<1e-4或最大绝对值与最小值的比率> 1e3时，使用科学记数法。默认值为False。

If True, always print floating point numbers using fixed point notation, in which case numbers equal to zero in the current precision will print as zero. If False, then scientific notation is used when absolute value of the smallest number is < 1e-4 or the ratio of the maximum absolute value to the minimum is > 1e3. The default is False.

**nanstr** : str, optional

浮点非字母数字的字符串表示形式（默认为nan）。

String representation of floating point not-a-number (default nan).

**infstr** : str, optional

浮点无穷大的字符串表示形式（默认inf）。

String representation of floating point infinity (default inf).

**sign** : string, either ‘-‘, ‘+’, or ‘ ‘, optional

控制浮点类型符号的打印。如果为“+”，则始终打印正值的符号。如果''，则始终在正值的符号位置打印空格（空格字符）。如果为“ - ”，则省略正值的符号字符。（默认' - '）

Controls printing of the sign of floating-point types. If ‘+’, always print the sign of positive values. If ‘ ‘, always prints a space (whitespace character) in the sign position of positive values. If ‘-‘, omit the sign character of positive values. (default ‘-‘)

**formatter** : dict of callables, optional

如果不是None，则键应指示相应格式化功能适用的类型。Callables应该返回一个字符串。未指定的类型（通过其对应的键）由默认格式化程序处理。可以设置格式化程序的各个类型是：



If not None, the keys should indicate the type(s) that the respective formatting function applies to. Callables should return a string. Types that are not specified (by their corresponding keys) are handled by the default formatters. Individual types for which a formatter can be set are:

- ‘bool’
- ‘int’
- ‘timedelta’ : a numpy.timedelta64
- ‘datetime’ : a numpy.datetime64
- ‘float’
- ‘longfloat’ : 128-bit floats
- ‘complexfloat’
- ‘longcomplexfloat’ : composed of two 128-bit floats
- ‘numpystr’ : types numpy.string_ and numpy.unicode_
- ‘object’ : np.object_ arrays
- ‘str’ : all other strings

可以用于一次设置一组类型的其他键是：

Other keys that can be used to set a group of types at once are:

- ‘all’ : sets all types
- ‘int_kind’ : sets ‘int’
- ‘float_kind’ : sets ‘float’ and ‘longfloat’
- ‘complex_kind’ : sets ‘complexfloat’ and ‘longcomplexfloat’
- ‘str_kind’ : sets ‘str’ and ‘numpystr’

**floatmode** : str, optional

控制浮点类型的精度选项的解释。可以采用以下值：

Controls the interpretation of the precision option for floating-point types. Can take the following values:

- **‘fixed’: Always print exactly precision fractional digits,**
>即使这会打印比指定值唯一所需的更多或更少的数字。

> even if this would print more or fewer digits than necessary to specify the value uniquely.

- **‘unique’: Print the minimum number of fractional digits necessary**
>唯一地表示每个值。不同的元素可以具有不同的数字位数。精度选项的值将 被忽略。

>to represent each value uniquely. Different elements may have a different number of digits. The value of the precision option is ignored.

- **‘maxprec’: Print at most precision fractional digits, but if**

>一个元素可以用较少的数字唯一地表示，只打印那么多。

>an element can be uniquely represented with fewer digits only print it with that many.


- **‘maxprec_equal’: Print at most precision fractional digits,**

>但是如果数组中的每个元素都可以使用相同数量的较少位数进行唯一表示，则对所有元素使用那么多位数。

>but if every element in the array can be uniquely represented with an equal number of fewer digits, use that many digits for all elements.

**legacy** : string or False, optional

如果设置为字符串'1.13'，则启用1.13传统打印模式。这通过在浮点的符号位置包含空格和0d数组的不同行为来近似numpy 1.13打印输出。如果设置为 False，则禁用传统模式。将忽略无法识别的字符串，并显示前向兼容性警告。

1.14.0版中的新功能。

If set to the string ‘1.13’ enables 1.13 legacy printing mode. This approximates numpy 1.13 print output by including a space in the sign position of floats and different behavior for 0d arrays. If set to False, disables legacy mode. Unrecognized strings will be ignored with a warning for forward compatibility.

New in version 1.14.0.

**注意：**

`formatter` is always reset with a call to `set_printoptions`.

## 示例

可以设置浮点精度：

In [4]:
import numpy as np

np.set_printoptions(precision=4)
print(np.array([1.123456789]))

[1.1235]


In [5]:
# 可以总结长数组：

np.set_printoptions(threshold=5)
print(np.arange(10))

[0 1 2 ... 7 8 9]


In [7]:
# 可以抑制小结果：

eps = np.finfo(float).eps
x = np.arange(4.)
x**2 - (x + eps)**2

array([-4.9304e-32, -4.4409e-16,  0.0000e+00,  0.0000e+00])

In [8]:
np.set_printoptions(suppress=True)
x**2 - (x + eps)**2

array([-0., -0.,  0.,  0.])

In [9]:
# 自定义格式化程序可用于根据需要显示数组元素：

np.set_printoptions(formatter={'all':lambda x: 'int: '+str(-x)})
x = np.arange(3)
x


array([int: 0, int: -1, int: -2])

In [10]:
np.set_printoptions()  # formatter gets reset
x

array([0, 1, 2])

In [11]:
# 要放回默认选项，您可以使用：

np.set_printoptions(edgeitems=3,infstr='inf',
                    linewidth=75, nanstr='nan', precision=8,
                    suppress=False, threshold=1000, formatter=None)

# numpy.get_printoptions
`numpy.get_printoptions()`

Return the current print options.

## Returns:	
print_opts : dict
Dictionary of current print options with keys

- precision : int
- threshold : int
- edgeitems : int
- linewidth : int
- suppress : bool
- nanstr : str
- infstr : str
- formatter : dict of callables
- sign : str

For a full description of these options, see set_printoptions.

# numpy.set_string_function
`numpy.set_string_function(f, repr=True)`

Set a Python function to be used when pretty printing arrays.

## Parameters:	
**f** : function or None

用于美观打印数组的函数。该函数应该期望单个数组参数并返回数组表示的字符串。如果为None，则将该函数重置为默认的NumPy函数以打印数组。

Function to be used to pretty print arrays. The function should expect a single array argument and return a string of the representation of the array. If None, the function is reset to the default NumPy function to print arrays.

**repr** : bool, optional

如果为True（默认值），__repr__则设置pretty printing（）的函数，如果为False，则设置返回默认字符串表示（__str__）的函数。

If True (default), the function for pretty printing (__repr__) is set, if False the function that returns the default string representation (__str__) is set.

## 示例

In [12]:
>>> def pprint(arr):
    return 'HA! - What are you going to do now?'

>>> np.set_string_function(pprint)
>>> a = np.arange(10)
>>> a

HA! - What are you going to do now?

In [13]:
>>> print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# 可以将函数重置为默认值：

np.set_string_function(None)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

epr影响漂亮的打印或正常的字符串表示。请注意，__repr__仍然受设置的影响，__str__ 因为返回的字符串中每个数组元素的宽度等于结果的长度__str__()。

In [17]:
>>> x = np.arange(4)
>>> np.set_string_function(lambda x:'random', repr=False)
>>> x.__str__()

'random'

In [19]:
x.__repr__()

'array([0, 1, 2, 3])'

# numpy.printoptions
`numpy.printoptions(*args, **kwargs)`

用于设置打印选项的上下文管理

设置with块范围的打印选项，并在最后恢复旧选项。有关可用选项的完整说明，请参阅set_printoptions。

Context manager for setting print options.

Set print options for the scope of the with block, and restore the old options at the end. See set_printoptions for the full description of available options.

## 示例

In [27]:
with np.printoptions(precision=2):
    print(np.array([2.0]) / 3)

random


In [51]:
# with-statement的as-子句给出了当前的打印选项：
# The `as-clause of the with-statement gives the current print options:

with np.printoptions(precision=2) as opts:
    assert opts == np.get_printoptions()    